"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";

interface FAQItem {
  id: number;
  question: string;
  answer: string;
}

const FAQ_DATA: FAQItem[] = [
  {
    id: 1,
    question: "Is Urganize live?",
    answer: "Not yet. We're in pre-launch and onboarding early users via demos."
  },
  {
    id: 2,
    question: "Who is this for?",
    answer: "Artist managers in Nigeria handling music releases."
  },
  {
    id: 3,
    question: "Is it free?",
    answer: "Yes — free during early access. Paid plans will come later."
  },
  {
    id: 4,
    question: "Do I need marketing experience?",
    answer: "No. Urganize guides you step by step."
  },
  {
    id: 5,
    question: "Is this just another task manager?",
    answer: "No. Tasks are generated by AI based on your release stage."
  },
  {
    id: 6,
    question: "What happens after I click \"Start Your Release\"?",
    answer: "You'll personally walk through Urganize live with the founder and see how it works for your workflow."
  }
];

export default function FAQ() {
  const [activeId, setActiveId] = useState<number | null>(null);

  return (
    <section className="py-32 px-6 bg-gradient-to-b from-transparent via-neutral-900/30 to-transparent">
      <div className="max-w-3xl mx-auto">
        
        {/* Header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-6xl font-black tracking-tighter mb-6">
            Questions?
          </h2>
          <p className="text-neutral-400 text-lg">
            Everything you need to know about Urganize.
          </p>
        </div>

        {/* FAQ Items */}
        <div className="space-y-4">
          {FAQ_DATA.map((item) => (
            <div
              key={item.id}
              className="rounded-2xl border border-white/5 bg-neutral-900/30 overflow-hidden"
            >
              <button
                onClick={() => setActiveId(activeId === item.id ? null : item.id)}
                className="w-full px-8 py-6 flex items-center justify-between text-left hover:bg-white/[0.02] transition-colors"
              >
                <span className="text-lg font-semibold pr-8">{item.question}</span>
                <div className={`flex-shrink-0 w-8 h-8 rounded-full border border-white/10 flex items-center justify-center transition-transform duration-300 ${
                  activeId === item.id ? 'rotate-45 bg-emerald-500 border-emerald-500' : ''
                }`}>
                  <svg 
                    className={`w-4 h-4 transition-colors ${activeId === item.id ? 'text-black' : 'text-white'}`} 
                    fill="none" 
                    viewBox="0 0 24 24" 
                    stroke="currentColor"
                  >
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 4v16m8-8H4" />
                  </svg>
                </div>
              </button>

              <AnimatePresence>
                {activeId === item.id && (
                  <motion.div
                    initial={{ height: 0, opacity: 0 }}
                    animate={{ height: "auto", opacity: 1 }}
                    exit={{ height: 0, opacity: 0 }}
                    transition={{ duration: 0.3, ease: [0.22, 1, 0.36, 1] }}
                    className="overflow-hidden"
                  >
                    <div className="px-8 pb-6 pt-2">
                      <div className="w-full h-px bg-gradient-to-r from-transparent via-emerald-500/20 to-transparent mb-6" />
                      <p className="text-neutral-300 text-lg leading-relaxed whitespace-pre-line">
                        {item.answer}
                      </p>
                    </div>
                  </motion.div>
                )}
              </AnimatePresence>
            </div>
          ))}
        </div>

        {/* Sign Up CTA 
        <div className="text-center mt-12">
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center">
            <a
              href="https://app.urganize.app/auth"
              className="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-2xl
                bg-emerald-500 text-black font-semibold text-lg
                hover:bg-emerald-400 hover:scale-105
                transition-all duration-300
                shadow-[0_0_30px_-10px_rgba(16,185,129,0.3)]"
            >
              Sign Up
              <svg
                className="w-5 h-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M13 7l5 5m0 0l-5 5m5-5H6"
                />
              </svg>
            </a>
            <a
              href="https://app.urganize.app/auth"
              className="inline-flex items-center justify-center gap-2 px-8 py-4 rounded-2xl
                bg-emerald-500/10 border border-emerald-500/30
                text-emerald-400 font-semibold text-lg
                hover:bg-emerald-500/20 hover:border-emerald-400
                transition-all duration-300"
            >
              Login
            </a>
          </div>
        </div>*/}
      </div>
    </section>
  );
}
