ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "role" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "teamSize" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "releaseVolume" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "primaryNeed" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "metadata" JSONB;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "isLaunchPartner" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "referralCode" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
